{{ config (
    materialized = 'ephemeral'
)}}

{#  Channel resolution moved into macros/erie_channel.sql — see there for why `source` stays
    primary and utm_source only breaks a tie, with the measured counts. B-prefixed codes
    added 2026-08-12 alongside their Roofing twins: BIL5/IL5 (Google), BSM3 (Outbrain),
    BSM6 (TikTok), BYLP/YLP (Yelp — real channel, but expect $0 spend against it).  #}
SELECT {{ erie_channel('source', 'utm_source', 'date') }} AS channel,
        date, 
        date_granularity, 
        office, 
        office_location, 
        CASE WHEN market IS NULL THEN '999 - Invalid' ELSE market END as sf_locations, 
        source,
        sub_source_id, 
        sub_source, 
        zip,
        {#  erie_type now follows the PRODUCT, not the source-code prefix.

            `source ~* 'B'` was only ever a proxy for "this lead is Basement", used because
            the daily file carried Roofing only. It is wrong in both directions, and both
            are measurable in the raw file since 2025-01-01:
              - 217 Roof leads carry a B-prefixed source (BIL2 73, BSMR 67, BSM5 28, ...)
                and were being labelled Basement. That is the entire 251 sf_leads currently
                sitting under erie_type='Basement' in blended — Roofing leads with no
                Basement spend to match.
              - 459 Basement leads carry a non-B source (SM3, IL2, IL5, SMD, ...) because
                a Roofing campaign generated a Basement sale. Those were dropped entirely.

            `prod` is authoritative, so use it. NULL prod (~20k rows, no product recorded)
            keeps the old proxy rather than silently defaulting to Roofing.

            NOTE the deliberate consequence: a Basement lead generated by a Roofing campaign
            is now erie_type='Basement' while the spend that produced it is
            erie_type='Roofing'. That is correct for product reporting and it is what the
            old prod filter already implied, but it means those leads have no matching
            Basement spend. Measured at 14 of 968 Google leads (1.4%) for May-Aug 2026 —
            immaterial, but it is why Basement CPL should be read at channel grain, not
            campaign grain, until the volume is understood. #}
        CASE WHEN prod = 'Basement Waterproofing' THEN 'Basement'
            WHEN prod = 'Roof' THEN 'Roofing'
            WHEN prod IS NULL AND source ~* 'B' AND source != 'BNA' THEN 'Basement'
            ELSE 'Roofing'
        END as erie_type,
        CASE WHEN source IN ('SMR','SM1','SM4','BSM4','IL3','BIL3','SM3','BSMR','BSM1','SM5','BSM5') THEN 'National'
            WHEN source IN ('SM','SMO','SM2','BSM','BSM2') THEN 'Local'
            WHEN source = 'RYT' THEN 'Retargeting'
            ELSE 'Other'
        END as market,
        CASE WHEN source IN ('SM2','SM4','SM1','SM','BSM','BSM2','BSM1') 
                OR (utm_source ~* 'facebook' AND utm_campaign !~* 'warm') THEN 'Prospecting'
            WHEN source IN ('SMR','SMO','BSMR')
                OR (utm_source ~* 'facebook' AND utm_campaign ~* 'warm') THEN 'Retargeting'
            WHEN source IN ('SMD','BSMD') OR (utm_source ~* 'google' AND utm_campaign ~* 'discovery') OR (utm_source ~* 'google' AND utm_campaign ~* 'demand gen') THEN 'Demand Gen'
            WHEN source IN ('PMX','BPMX','PMX2') OR (utm_source ~* 'google' AND COALESCE(advertising_channel_type, nm_channel_type) = 'PERFORMANCE_MAX') THEN 'Performance Max'
            WHEN source IN ('IL2','BIL2','IL3','BIL3','IL5','BIL5') OR (utm_source ~* 'google' AND COALESCE(advertising_channel_type, nm_channel_type) = 'SEARCH')THEN 'Search'
			WHEN source IN ('BNA') THEN 'Audience'
        END as campaign_type,
        {{ region_bucket(['COALESCE(bg_campaign_name, nm_campaign_name)::VARCHAR', 'utm_campaign']) }} as region_bucket,
        {{ service_type_bucket(['COALESCE(gb_ad_group_name, utm_ad_group_name)::VARCHAR', 'utm_term']) }} as service_type,
        dispo,
        call_disposition,
        status_detail,
        utm_medium,
        CASE WHEN source IN ('PMX','BPMX','IL2','SMD','BIL2','BSMD') OR utm_source ~* 'google' THEN COALESCE(bg_campaign_name, nm_campaign_name)::VARCHAR
            WHEN source IN ('IL3','BIL3','BNA','PMX2') OR utm_source ~* 'bing' THEN COALESCE(bg_campaign_name, nm_campaign_name)::VARCHAR
            WHEN utm_campaign_id = 6930690664241 THEN 'Soc - Meta - Roofing - Prospecting - National - Florida Regional - Lead - CBO (Lifetime) Campaign'
	  		WHEN utm_campaign_id = 6931185343441 THEN 'Soc - Meta - Roofing - Prospecting - National - Great Lakes and East Great Lakes Regional - Instant Form - Lifetime'
	  	  	WHEN utm_campaign_id = 6930683609841 THEN 'Soc - Meta - Roofing - Prospecting - National - Northeast Regional - Lead - CBO (Lifetime) Campaign'
            {#  Meta path: prefer the current platform name resolved by campaign_id (bg,
                extended below with facebook_campaigns) over the raw utm_campaign text, which
                is hardcoded in the Instant Form and goes stale whenever a campaign is
                duplicated/renamed. utm_campaign_id itself is reliably populated on Meta
                (unlike Basement), so this is a straight id join, no name-normalization needed. #}
            ELSE COALESCE(bg_campaign_name, utm_campaign)::VARCHAR
        END as utm_campaign,
        CASE WHEN source IN ('PMX','BPMX','IL2','SMD','BIL2','BSMD') OR utm_source ~* 'google' THEN COALESCE(gb_ad_group_name, utm_ad_group_name)::VARCHAR
            WHEN source IN ('IL3','BIL3') OR (utm_source ~* 'bing' AND source NOT IN ('BNA','PMX2')) THEN COALESCE(gb_ad_group_name, utm_ad_group_name)::VARCHAR
			WHEN utm_source ~* 'bing' AND source IN ('BNA','PMX2') THEN NULL
            ELSE utm_term::VARCHAR
        END as utm_term,
        utm_content::VARCHAR,
        {#  Roofing and Basement put different things in utm_term, so the two slots have to
            be filled from different columns to line the grains up.

              Roofing  utm_term = the numeric ad_group_id, resolved to a name by the gb join
                       above; utm_keyword = the keyword (Bing only).
              Basement utm_term = the SEARCH TERM text — verified never a numeric id
                       (0 of 2,457 Google rows, 1 of 353 Bing, Jan-Aug 2026) — while the ad
                       group arrives separately as utm_ad_group_name (534 Google / 76 Bing)
                       and utm_keyword is barely wired up yet (127 Google / 50 Bing).

            So the ad-group slot takes utm_ad_group_name (done above) and the search term
            falls through to utm_keyword here, which is the closest Roofing equivalent that
            exists. Meta has neither: utm_term is the ad set name and the creative is in
            utm_content, which already lines up with Roofing.  #}
        CASE WHEN utm_source ~* 'bing' AND source NOT IN ('BNA','PMX2') THEN COALESCE(utm_keyword, utm_term)
            WHEN utm_source ~* 'google' AND gb_ad_group_name IS NULL THEN COALESCE(utm_keyword, utm_term)
            ELSE NULL
        END AS utm_keyword,
        '' as utm_match_type,
        utm_placement,
        utm_discount,
        utm_lp_variant,
		utm_msclk_id,
        {{ blended_metrics({
            'sf_leads': 'COALESCE(SUM(leads)::int,0)::int',
            'calls': 'COALESCE(SUM(calls),0)',
            'appointments': 'COALESCE(SUM(appointments),0)',
            'demos': 'COALESCE(SUM(demos),0)',
            'down_payments': 'COALESCE(SUM(down_payments),0)',
            'closed_deals': 'COALESCE(SUM(closed_deals),0)',
            'gross': 'COALESCE(SUM(gross),0)',
            'net': 'COALESCE(SUM(net),0)',
            'workable_leads': 'COALESCE(SUM(workable_leads),0)',
            'hits': 'COALESCE(SUM(hits),0)',
            'issues': 'COALESCE(SUM(issues),0)',
            'ooa_leads': 'COALESCE(SUM(ooa_leads),0)',
            'net_sale_count': 'COALESCE(SUM(net_sale_count),0)',
            'set_value': 'COALESCE(SUM(set_value),0)',
            'gross_sale_count': 'COALESCE(SUM(gross_sale_count),0)'
        }) }}
    FROM (SELECT *, COALESCE(utm_campaign_id::VARCHAR,utm_campaign) as utm_campaign_id_adj
            FROM {{ source('reporting','salesforce_performance') }}) s
    LEFT JOIN (SELECT campaign_id::VARCHAR as campaign_id, campaign_name as bg_campaign_name, advertising_channel_type
            FROM {{ ref('googleads_campaigns') }}
            UNION ALL
            SELECT campaign_id::VARCHAR as campaign_id, campaign_name as bg_campaign_name, NULL as advertising_channel_type
            FROM {{ ref('bingads_campaigns') }}
            UNION ALL
            SELECT campaign_id::VARCHAR as campaign_id, campaign_name as bg_campaign_name, NULL as advertising_channel_type
            FROM {{ ref('facebook_campaigns') }}
            ) bg ON s.utm_campaign_id_adj = bg.campaign_id
    {#  NAME-BASED CAMPAIGN JOIN — the Basement path.

        The id join above resolves Roofing, which carries utm_campaign_id. Basement does
        not: utm_campaign_id is populated on 0 of 14,230 facebook rows and 591 of 8,777
        google rows. Basement carries the campaign NAME instead, so it is joined on a
        normalised name key (see macros/normalize_campaign_name.sql for why raw names do
        not match).

        Aggregated to one row per key before joining, so a name that exists on more than one
        platform cannot fan out the lead rows. The id join still wins wherever it resolves —
        this is a COALESCE fallback, so Roofing behaviour is unchanged.  #}
    LEFT JOIN (SELECT {{ normalize_campaign_name('campaign_name') }} as name_key,
                      MAX(campaign_name) as nm_campaign_name,
                      MAX(advertising_channel_type) as nm_channel_type
            FROM (SELECT campaign_name, advertising_channel_type FROM {{ ref('googleads_campaigns') }}
                  UNION ALL
                  SELECT campaign_name, NULL as advertising_channel_type FROM {{ ref('bingads_campaigns') }}
                  UNION ALL
                  SELECT campaign_name, NULL as advertising_channel_type FROM {{ ref('facebook_campaigns') }})
            WHERE campaign_name IS NOT NULL AND campaign_name <> ''
            GROUP BY 1
            ) nm ON {{ normalize_campaign_name('s.utm_campaign') }} = nm.name_key
                AND bg.campaign_id IS NULL
    LEFT JOIN (SELECT ad_group_id::VARCHAR as ad_group_id, ad_group_name as gb_ad_group_name
            FROM {{ ref('googleads_ad_groups') }}
            UNION ALL
            SELECT ad_group_id::VARCHAR as ad_group_id, ad_group_name as gb_ad_group_name
            FROM {{ ref('bingads_ad_groups') }}
            UNION ALL
            SELECT asset_group_id::VARCHAR as ad_group_id, asset_group_name as gb_ad_group_name
            FROM {{ ref('googleads_asset_groups') }}
            ) gb ON s.utm_term = gb.ad_group_id
    WHERE date >= '2022-12-01'
    GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
